---
# This file contains all available configurations. Only one configuration gets used at runtime.
#TODO infer about geenric way (format string?) to define DB url
DEV:
  db_type: sqlite
  db_name: data/dev-data.sqlite
  drop_db: true
  log_level: DEBUG
  log_output: dev.log
  log_format: '%(asctime)s %(levelname)s %(name)s %(message)s'
  log_style: '%'
  log_dateformat: '%Y-%m-%d %H:%M:%S'

TEST:


TRAIN:


PROD:


...
